include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: false
    constant_identifier_names: false
    avoid_function_literals_in_foreach_calls: false
    always_declare_return_types: true

analyzer:
  # exclude:
  #  - generator/generate.dart
  errors:
    invalid_assignment: warning
    missing_return: error
    dead_code: info
    todo: info
